In [154]:
import pandas as pd

In [155]:
s = pd.Series([1,2,3,4,5])
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [156]:
data=[[1,444,'abc'],[5,444,'abc'],[1,444,'abc'],[66,444,'abc']]
df=pd.DataFrame(data,columns=["Id","salary","department"])
display(df)

   Id  salary department
0   1     444        abc
1   5     444        abc
2   1     444        abc
3  66     444        abc

In [157]:
data={"id":[1,2,4],'salary':[444,555,666],'department':['abc','abc','dcf']}
print(data)

{'id': [1, 2, 4], 'salary': [444, 555, 666], 'department': ['abc', 'abc', 'dcf']}

In [158]:
# Transfer  dictionary to dataframe
df2=pd.DataFrame(data)
display(df2)

   id  salary department
0   1     444        abc
1   2     555        abc
2   4     666        dcf

In [159]:
type(df2)

pandas.DataFrame

In [160]:
print(df2.columns)

Index(['id', 'salary', 'department'], dtype='str')

In [161]:
columns_name=['a','b','c']
df2.columns=columns_name

display(df2)

   a    b    c
0  1  444  abc
1  2  555  abc
2  4  666  dcf

In [162]:
df.dtypes

Id            int64
salary        int64
department      str
dtype: object

In [163]:
df2['a']=df2['a'].astype("category")
display(df2)
print(df2.dtypes)

   a    b    c
0  1  444  abc
1  2  555  abc
2  4  666  dcf

a    category
b       int64
c         str
dtype: object

In [164]:
cols=['a','b']
df2[cols]=df2[cols].astype('category')
print(df2)

   a    b    c
0  1  444  abc
1  2  555  abc
2  4  666  dcf

In [165]:
# return all wors except the last row
df2.head(-1)

   a    b    c
0  1  444  abc
1  2  555  abc

In [166]:
df2.tail()

   a    b    c
0  1  444  abc
1  2  555  abc
2  4  666  dcf

In [167]:
# Deal only with numerical values
df2.describe(include='category')

        a    b
count   3    3
unique  3    3
top     1  444
freq    1    1

In [168]:
df['Id']

0     1
1     5
2     1
3    66
Name: Id, dtype: int64

In [169]:
df.Id

0     1
1     5
2     1
3    66
Name: Id, dtype: int64

In [170]:
print(df['Id'].unique())
print(df['Id'].unique().sum())

[ 1  5 66]
72

In [171]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          4 non-null      int64
 1   salary      4 non-null      int64
 2   department  4 non-null      str
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [172]:
print(df2['c'].max())
print(df2['c'].idxmax())

dcf
2

In [173]:
df2['b'].value_counts()

b
444    1
555    1
666    1
Name: count, dtype: int64

In [174]:
x=df2.values
print(x)
print(type(x))

[[1 444 'abc']
 [2 555 'abc']
 [4 666 'dcf']]
<class 'numpy.ndarray'>

In [176]:
sort_df=df.sort_values(by='Id',ascending=False)
print(sort_df)

   Id  salary department
3  66     444        abc
1   5     444        abc
0   1     444        abc
2   1     444        abc

In [178]:
df['Id'].apply(lambda x : x*2)
display(df2)

   a    b    c
0  1  444  abc
1  2  555  abc
2  4  666  dcf

In [181]:
display(df)
df.Id.iloc[3]

   Id  salary department
0   1     444        abc
1   5     444        abc
2   1     444        abc
3  66     444        abc

np.int64(66)

In [189]:
print(df.iloc[:])
print()
print("Features\n",df.iloc[:,0:2])
print("Target\n",df.iloc[:,-1])

   Id  salary department
0   1     444        abc
1   5     444        abc
2   1     444        abc
3  66     444        abc

Features
    Id  salary
0   1     444
1   5     444
2   1     444
3  66     444
Target
 0    abc
1    abc
2    abc
3    abc
Name: department, dtype: str

In [196]:
x=df.drop(['department'],axis=1)
print(x)
x=x.add([1,2],axis=1)
print(x)

   Id  salary
0   1     444
1   5     444
2   1     444
3  66     444
   Id  salary
0   2     446
1   6     446
2   2     446
3  67     446